services:
   search:
      build: ./search
      image: ghcr.io/nashtech-garage/yas-search:latest
      environment:
         - ELASTICSEARCH_URL=${ELASTICSEARCH_URL:-elasticsearch:9200}
         - SERVER_SERVLET_CONTEXT_PATH=/search
         - YAS_PUBLIC_URL=${YAS_PUBLIC_API_URL}/search
         - YAS_SERVICES_PRODUCT
         - SERVER_PORT
         - LOGGING_CONFIG
         - JAVA_TOOL_OPTIONS
         - OTEL_EXPORTER_OTLP_ENDPOINT
         - OTEL_EXPORTER_OTLP_PROTOCOL
         - OTEL_EXPORTER_OTLP_METRICS_TEMPORALITY_PREFERENCE
         - OTEL_RESOURCE_ATTRIBUTES
         - OTEL_SERVICE_NAME=search-service
         - OTEL_LOGS_EXPORTER
         - OTEL_TRACES_EXPORTER
         - OTEL_METRICS_EXPORTER
         - OTEL_INSTRUMENTATION_LOGBACK-MDC_ADD-BAGGAGE
         - OTEL_JAVAAGENT_LOGGING
         - OTEL_JAVAAGENT_ENABLED
         - OTEL_JAVAAGENT_DEBUG
      volumes:
         - ./docker/libs/opentelemetry-javaagent.jar:/opentelemetry-javaagent.jar
         - ./deployment/app-config:/app-config
      depends_on:
         elasticsearch:
            condition: service_healthy
         # If you start Kafka via the main compose file and rely on Kafka topics:
         #  kafka:
         #     condition: service_started
      entrypoint: [ "./wait-for-it.sh", "elasticsearch:9200", "--timeout=300", "--", "java", "-jar", "/app.jar" ]
      networks:
         - yas-network
   elasticsearch:
      image: elasticsearch:9.1.0
      volumes:
         - esdata:/usr/share/elasticsearch/data
      environment:
         - "ES_JAVA_OPTS=-Xms512m -Xmx512m"
         - xpack.security.enabled=false
         - "discovery.type=single-node"
      healthcheck:
         test: [ "CMD-SHELL", "curl -fsS http://localhost:9200 >/dev/null || exit 1" ]
         interval: 5s
         timeout: 3s
         retries: 30
      ports:
         - "9200:9200"
         - "9300:9300"
      networks:
         - yas-network

networks:
   yas-network:
      name: yas-network
      external: true

volumes:
   esdata:
