server:
  port: 8087
spring:
  cloud:
    gateway:
      routes:
        - id: api
          uri: http://localhost:8080
          predicates:
            - Path=/api/**
          filters:
            - RewritePath=/api/(?<segment>.*), /$\{segment}
            - TokenRelay=
        - id: nextjs
          uri: http://localhost:3000
          predicates:
            - Path=/**
  security:
    oauth2:
      client:
        provider:
          keycloak:
            issuer-uri: http://identity/auth/realms/Yas
        registration:
          api-client:
            provider: keycloak
            client-id: backoffice-bff
            client-secret: cnzK70aLGuuWAdQOUgkdMTlYDCDv1T9V
            scope:
              - email
              - profile
              - roles
